version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      APP_ENV: local
      APP_KEY: dpg-cu7auj23esus73fiabo0-a
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: postgresql://stephy:hL7X8QLckUDWgaxmMFTszIgzVAvW2gQM@dpg-cu7auj23esus73fiabo0-a/decameron_hotel
      DB_PORT: 5432
      DB_DATABASE: decameron_hotel_glio
      DB_USERNAME: stephy
      DB_PASSWORD: hL7X8QLckUDWgaxmMFTszIgzVAvW2gQM
