version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      APP_ENV: local
      APP_KEY: base64:2QUflnfWUQOEh8N1D/JegT+iRMx4ZKCcF3kAXLwJHus=
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: postgresql://stephy:0FQaKkSuiqpwe5qGmrhz8pKHGVjVzvTW@dpg-ct8r0q2j1k6c73eaqlqg-a/decameron_hotel
      DB_PORT: 5432
      DB_DATABASE: decameron_hotel
      DB_USERNAME: stephy
      DB_PASSWORD: 0FQaKkSuiqpwe5qGmrhz8pKHGVjVzvTW
