version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      APP_ENV: local
      APP_KEY: base64:YOUR_APP_KEY
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: dpg-ct8r0q2j1k6c73eaqlqg-a
      DB_PORT: 5432
      DB_DATABASE: decameron_hotel
      DB_USERNAME: stephy
      DB_PASSWORD: 0FQaKkSuiqpwe5qGmrhz8pKHGVjVzvTW
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: laravel_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: decameron_hotel
      POSTGRES_USER: stephy
      POSTGRES_PASSWORD: 0FQaKkSuiqpwe5qGmrhz8pKHGVjVzvTW
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
